// Code generated by protoc-gen-go. DO NOT EDIT.
// source: deployer/actions/access.proto

/*
Package actions is a generated protocol buffer package.

It is generated from these files:
	deployer/actions/access.proto

It has these top-level messages:
	ListApplicationsByUsernameRequest
	ListApplicationsByUsernameReply
	CreateApplicationRequest
	CreateApplicationReply
	UpdateDeploymentImageRequest
	UpdateDeploymentImageReply
	GetApplicationByIdRequest
	GetApplicationByIdResponse
*/
package actions

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import deployer "code.ysitd.cloud/grpc/schema/deployer/models"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ListApplicationsByUsernameRequest struct {
	Username string `protobuf:"bytes,1,opt,name=username" json:"username,omitempty"`
}

func (m *ListApplicationsByUsernameRequest) Reset()         { *m = ListApplicationsByUsernameRequest{} }
func (m *ListApplicationsByUsernameRequest) String() string { return proto.CompactTextString(m) }
func (*ListApplicationsByUsernameRequest) ProtoMessage()    {}
func (*ListApplicationsByUsernameRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{0}
}

func (m *ListApplicationsByUsernameRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

type ListApplicationsByUsernameReply struct {
	Apps []*deployer.Application `protobuf:"bytes,1,rep,name=apps" json:"apps,omitempty"`
}

func (m *ListApplicationsByUsernameReply) Reset()                    { *m = ListApplicationsByUsernameReply{} }
func (m *ListApplicationsByUsernameReply) String() string            { return proto.CompactTextString(m) }
func (*ListApplicationsByUsernameReply) ProtoMessage()               {}
func (*ListApplicationsByUsernameReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *ListApplicationsByUsernameReply) GetApps() []*deployer.Application {
	if m != nil {
		return m.Apps
	}
	return nil
}

type CreateApplicationRequest struct {
	App *deployer.Application `protobuf:"bytes,1,opt,name=app" json:"app,omitempty"`
}

func (m *CreateApplicationRequest) Reset()                    { *m = CreateApplicationRequest{} }
func (m *CreateApplicationRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateApplicationRequest) ProtoMessage()               {}
func (*CreateApplicationRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *CreateApplicationRequest) GetApp() *deployer.Application {
	if m != nil {
		return m.App
	}
	return nil
}

type CreateApplicationReply struct {
	Success bool `protobuf:"varint,1,opt,name=success" json:"success,omitempty"`
}

func (m *CreateApplicationReply) Reset()                    { *m = CreateApplicationReply{} }
func (m *CreateApplicationReply) String() string            { return proto.CompactTextString(m) }
func (*CreateApplicationReply) ProtoMessage()               {}
func (*CreateApplicationReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *CreateApplicationReply) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type UpdateDeploymentImageRequest struct {
	Id         string               `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Deployment *deployer.Deployment `protobuf:"bytes,2,opt,name=deployment" json:"deployment,omitempty"`
}

func (m *UpdateDeploymentImageRequest) Reset()                    { *m = UpdateDeploymentImageRequest{} }
func (m *UpdateDeploymentImageRequest) String() string            { return proto.CompactTextString(m) }
func (*UpdateDeploymentImageRequest) ProtoMessage()               {}
func (*UpdateDeploymentImageRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *UpdateDeploymentImageRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *UpdateDeploymentImageRequest) GetDeployment() *deployer.Deployment {
	if m != nil {
		return m.Deployment
	}
	return nil
}

type UpdateDeploymentImageReply struct {
	Success bool `protobuf:"varint,1,opt,name=success" json:"success,omitempty"`
}

func (m *UpdateDeploymentImageReply) Reset()                    { *m = UpdateDeploymentImageReply{} }
func (m *UpdateDeploymentImageReply) String() string            { return proto.CompactTextString(m) }
func (*UpdateDeploymentImageReply) ProtoMessage()               {}
func (*UpdateDeploymentImageReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *UpdateDeploymentImageReply) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type GetApplicationByIdRequest struct {
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
}

func (m *GetApplicationByIdRequest) Reset()                    { *m = GetApplicationByIdRequest{} }
func (m *GetApplicationByIdRequest) String() string            { return proto.CompactTextString(m) }
func (*GetApplicationByIdRequest) ProtoMessage()               {}
func (*GetApplicationByIdRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *GetApplicationByIdRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type GetApplicationByIdResponse struct {
	Exists bool                  `protobuf:"varint,1,opt,name=exists" json:"exists,omitempty"`
	App    *deployer.Application `protobuf:"bytes,2,opt,name=app" json:"app,omitempty"`
}

func (m *GetApplicationByIdResponse) Reset()                    { *m = GetApplicationByIdResponse{} }
func (m *GetApplicationByIdResponse) String() string            { return proto.CompactTextString(m) }
func (*GetApplicationByIdResponse) ProtoMessage()               {}
func (*GetApplicationByIdResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *GetApplicationByIdResponse) GetExists() bool {
	if m != nil {
		return m.Exists
	}
	return false
}

func (m *GetApplicationByIdResponse) GetApp() *deployer.Application {
	if m != nil {
		return m.App
	}
	return nil
}

func init() {
	proto.RegisterType((*ListApplicationsByUsernameRequest)(nil), "deployer.ListApplicationsByUsernameRequest")
	proto.RegisterType((*ListApplicationsByUsernameReply)(nil), "deployer.ListApplicationsByUsernameReply")
	proto.RegisterType((*CreateApplicationRequest)(nil), "deployer.CreateApplicationRequest")
	proto.RegisterType((*CreateApplicationReply)(nil), "deployer.CreateApplicationReply")
	proto.RegisterType((*UpdateDeploymentImageRequest)(nil), "deployer.UpdateDeploymentImageRequest")
	proto.RegisterType((*UpdateDeploymentImageReply)(nil), "deployer.UpdateDeploymentImageReply")
	proto.RegisterType((*GetApplicationByIdRequest)(nil), "deployer.GetApplicationByIdRequest")
	proto.RegisterType((*GetApplicationByIdResponse)(nil), "deployer.GetApplicationByIdResponse")
}

func init() { proto.RegisterFile("deployer/actions/access.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 348 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x92, 0xc1, 0x4b, 0xe3, 0x40,
	0x14, 0xc6, 0x49, 0xba, 0x74, 0xbb, 0x6f, 0x61, 0x0f, 0x61, 0x2d, 0x31, 0x2a, 0xd6, 0x5c, 0xac,
	0x88, 0x09, 0x54, 0xf1, 0x2a, 0xb6, 0x82, 0x14, 0x7b, 0x90, 0x40, 0x2f, 0x82, 0x87, 0x71, 0xe6,
	0x51, 0x07, 0x92, 0xcc, 0x98, 0x37, 0x01, 0xf3, 0xdf, 0x4b, 0x87, 0x24, 0x0d, 0xd2, 0xd6, 0xe3,
	0xcb, 0xfb, 0xe5, 0x9b, 0xdf, 0x7c, 0x0c, 0x9c, 0x08, 0xd4, 0xa9, 0xaa, 0xb0, 0x88, 0x19, 0x37,
	0x52, 0xe5, 0x14, 0x33, 0xce, 0x91, 0x28, 0xd2, 0x85, 0x32, 0xca, 0x1b, 0x34, 0xeb, 0xe0, 0xa8,
	0x05, 0x33, 0x25, 0x30, 0xa5, 0xd8, 0x54, 0x1a, 0x6b, 0x2c, 0xbc, 0x83, 0xb3, 0x85, 0x24, 0x73,
	0xaf, 0x75, 0x2a, 0x39, 0xb3, 0x39, 0xd3, 0x6a, 0x49, 0x58, 0xe4, 0x2c, 0xc3, 0x04, 0x3f, 0x4a,
	0x24, 0xe3, 0x05, 0x30, 0x28, 0xeb, 0x4f, 0xbe, 0x33, 0x72, 0xc6, 0x7f, 0x92, 0x76, 0x0e, 0x17,
	0x70, 0xba, 0x2f, 0x40, 0xa7, 0x95, 0x77, 0x01, 0xbf, 0x98, 0xd6, 0xe4, 0x3b, 0xa3, 0xde, 0xf8,
	0xef, 0xe4, 0x20, 0x6a, 0x7c, 0xa2, 0xce, 0x4f, 0x89, 0x45, 0xc2, 0x19, 0xf8, 0xb3, 0x02, 0x99,
	0xc1, 0xee, 0xaa, 0xb6, 0x38, 0x87, 0x1e, 0xd3, 0xda, 0x0a, 0xec, 0x4c, 0x59, 0x13, 0xe1, 0x04,
	0x86, 0x5b, 0x42, 0xd6, 0x26, 0x3e, 0xfc, 0xa6, 0xd2, 0xb6, 0x64, 0x63, 0x06, 0x49, 0x33, 0x86,
	0x02, 0x8e, 0x97, 0x5a, 0x30, 0x83, 0x0f, 0x36, 0x36, 0xc3, 0xdc, 0xcc, 0x33, 0xb6, 0x6a, 0x2b,
	0xf8, 0x07, 0xae, 0x14, 0xf5, 0xe5, 0x5d, 0x29, 0xbc, 0x1b, 0x00, 0xd1, 0x92, 0xbe, 0x6b, 0x9d,
	0xfe, 0x6f, 0x9c, 0x36, 0x29, 0x49, 0x87, 0x0b, 0x6f, 0x21, 0xd8, 0x71, 0xca, 0x7e, 0xbb, 0x4b,
	0x38, 0x7c, 0xc4, 0x6e, 0xc7, 0xd3, 0x6a, 0x2e, 0x76, 0xa8, 0x85, 0xaf, 0x10, 0x6c, 0x83, 0x49,
	0xab, 0x9c, 0xd0, 0x1b, 0x42, 0x1f, 0x3f, 0x25, 0x99, 0xe6, 0x8c, 0x7a, 0x6a, 0xda, 0x75, 0x7f,
	0x6a, 0x77, 0xfa, 0x04, 0x3e, 0x4f, 0x55, 0x29, 0xa2, 0x8a, 0xa4, 0x11, 0xd1, 0xaa, 0xd0, 0x3c,
	0x62, 0x9c, 0xab, 0x32, 0x37, 0xcf, 0xce, 0xcb, 0x15, 0x57, 0x02, 0xeb, 0x95, 0xc5, 0xe2, 0x35,
	0x10, 0x13, 0x7f, 0xc7, 0x8c, 0xc5, 0xdf, 0x9f, 0xec, 0x5b, 0xdf, 0xbe, 0xc2, 0xeb, 0xaf, 0x00,
	0x00, 0x00, 0xff, 0xff, 0xc4, 0xf5, 0x6e, 0xe5, 0xcd, 0x02, 0x00, 0x00,
}
