# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: judge/grpc.proto for package 'judge'

require 'grpc'
require 'judge/grpc_pb'

module Judge
  module Judge
    class Service

      include GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'judge.Judge'

      # Subject CURD
      rpc :createSubject, Subject, SubjectMutationReply
      rpc :deleteSubject, SubjectSelector, SubjectMutationReply
      rpc :updateSubject, UpdateSubjectRequest, SubjectMutationReply
      rpc :getSubject, SubjectSelector, Subject
      # Resource CURD
      rpc :getResource, ResourceSelector, Resource
      rpc :deleteResource, ResourceSelector, ResourceMutationReply
      rpc :updateResource, UpdateResourceRequest, ResourceMutationReply
      rpc :createResource, Resource, ResourceMutationReply
      # Judge Service
      rpc :validatePolicy, AccessRequest, AccessReply
    end

    Stub = Service.rpc_stub_class
  end
end
