# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: judge/grpc.proto

require 'google/protobuf'

require 'judge/models/types_pb'
require 'judge/actions/judge_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
end

module Judge
end
