// Code generated by protoc-gen-go. DO NOT EDIT.
// source: judge/judge.proto

/*
Package judge is a generated protocol buffer package.

It is generated from these files:
	judge/judge.proto

It has these top-level messages:
	AccessRequest
	AccessReply
*/
package judge

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type AccessRequest struct {
	Subject  string `protobuf:"bytes,1,opt,name=subject" json:"subject,omitempty"`
	Action   string `protobuf:"bytes,2,opt,name=action" json:"action,omitempty"`
	Resource string `protobuf:"bytes,3,opt,name=resource" json:"resource,omitempty"`
	Token    string `protobuf:"bytes,4,opt,name=token" json:"token,omitempty"`
}

func (m *AccessRequest) Reset()                    { *m = AccessRequest{} }
func (m *AccessRequest) String() string            { return proto.CompactTextString(m) }
func (*AccessRequest) ProtoMessage()               {}
func (*AccessRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *AccessRequest) GetSubject() string {
	if m != nil {
		return m.Subject
	}
	return ""
}

func (m *AccessRequest) GetAction() string {
	if m != nil {
		return m.Action
	}
	return ""
}

func (m *AccessRequest) GetResource() string {
	if m != nil {
		return m.Resource
	}
	return ""
}

func (m *AccessRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type AccessReply struct {
	Allow  bool   `protobuf:"varint,1,opt,name=allow" json:"allow,omitempty"`
	Reason string `protobuf:"bytes,2,opt,name=reason" json:"reason,omitempty"`
}

func (m *AccessReply) Reset()                    { *m = AccessReply{} }
func (m *AccessReply) String() string            { return proto.CompactTextString(m) }
func (*AccessReply) ProtoMessage()               {}
func (*AccessReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *AccessReply) GetAllow() bool {
	if m != nil {
		return m.Allow
	}
	return false
}

func (m *AccessReply) GetReason() string {
	if m != nil {
		return m.Reason
	}
	return ""
}

func init() {
	proto.RegisterType((*AccessRequest)(nil), "judge.AccessRequest")
	proto.RegisterType((*AccessReply)(nil), "judge.AccessReply")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Judge service

type JudgeClient interface {
	ValidatePolicy(ctx context.Context, in *AccessRequest, opts ...grpc.CallOption) (*AccessReply, error)
}

type judgeClient struct {
	cc *grpc.ClientConn
}

func NewJudgeClient(cc *grpc.ClientConn) JudgeClient {
	return &judgeClient{cc}
}

func (c *judgeClient) ValidatePolicy(ctx context.Context, in *AccessRequest, opts ...grpc.CallOption) (*AccessReply, error) {
	out := new(AccessReply)
	err := grpc.Invoke(ctx, "/judge.Judge/validatePolicy", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Judge service

type JudgeServer interface {
	ValidatePolicy(context.Context, *AccessRequest) (*AccessReply, error)
}

func RegisterJudgeServer(s *grpc.Server, srv JudgeServer) {
	s.RegisterService(&_Judge_serviceDesc, srv)
}

func _Judge_ValidatePolicy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AccessRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JudgeServer).ValidatePolicy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/judge.Judge/ValidatePolicy",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JudgeServer).ValidatePolicy(ctx, req.(*AccessRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Judge_serviceDesc = grpc.ServiceDesc{
	ServiceName: "judge.Judge",
	HandlerType: (*JudgeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "validatePolicy",
			Handler:    _Judge_ValidatePolicy_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "judge/judge.proto",
}

func init() { proto.RegisterFile("judge/judge.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 232 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x90, 0xc1, 0x4a, 0x03, 0x31,
	0x10, 0x86, 0x5d, 0x75, 0x6b, 0x1d, 0x51, 0x30, 0x94, 0x12, 0x7a, 0x92, 0x3d, 0x88, 0xa7, 0x15,
	0xf4, 0xa8, 0x17, 0x0b, 0x5e, 0x3c, 0x2d, 0xfb, 0x06, 0x69, 0x76, 0x28, 0x5b, 0x43, 0x67, 0xcd,
	0x24, 0xca, 0xbe, 0xbd, 0x64, 0xe2, 0x2a, 0xf6, 0x12, 0xf8, 0xf2, 0x0f, 0xf9, 0x32, 0x3f, 0x5c,
	0xef, 0x62, 0xb7, 0xc5, 0x7b, 0x39, 0xeb, 0xc1, 0x53, 0x20, 0x55, 0x0a, 0x54, 0x0c, 0x97, 0x2f,
	0xd6, 0x22, 0x73, 0x8b, 0x1f, 0x11, 0x39, 0x28, 0x0d, 0x67, 0x1c, 0x37, 0x3b, 0xb4, 0x41, 0x17,
	0x37, 0xc5, 0xdd, 0x79, 0x3b, 0xa1, 0x5a, 0xc2, 0xcc, 0xd8, 0xd0, 0xd3, 0x5e, 0x1f, 0x4b, 0xf0,
	0x43, 0x6a, 0x05, 0x73, 0x8f, 0x4c, 0xd1, 0x5b, 0xd4, 0x27, 0x92, 0xfc, 0xb2, 0x5a, 0x40, 0x19,
	0xe8, 0x1d, 0xf7, 0xfa, 0x54, 0x82, 0x0c, 0xd5, 0x13, 0x5c, 0x4c, 0xd2, 0xc1, 0x8d, 0x69, 0xc8,
	0x38, 0x47, 0x5f, 0x22, 0x9c, 0xb7, 0x19, 0x92, 0xce, 0xa3, 0xe1, 0x3f, 0x5d, 0xa6, 0x87, 0x57,
	0x28, 0xdf, 0xd2, 0xd7, 0xd5, 0x33, 0x5c, 0x7d, 0x1a, 0xd7, 0x77, 0x26, 0x60, 0x43, 0xae, 0xb7,
	0xa3, 0x5a, 0xd4, 0x79, 0xc3, 0x7f, 0x1b, 0xad, 0xd4, 0xc1, 0xed, 0xe0, 0xc6, 0xea, 0x68, 0x7d,
	0x0b, 0x4b, 0xeb, 0x28, 0x76, 0xf5, 0xc8, 0x7d, 0xe8, 0xea, 0xad, 0x1f, 0x6c, 0x9e, 0x5b, 0x83,
	0x3c, 0xdf, 0xa4, 0x96, 0x9a, 0x62, 0x33, 0x93, 0xba, 0x1e, 0xbf, 0x03, 0x00, 0x00, 0xff, 0xff,
	0xe2, 0xc1, 0x36, 0x68, 0x43, 0x01, 0x00, 0x00,
}
