// Code generated by protoc-gen-go. DO NOT EDIT.
// source: judge/judge.proto

/*
Package judge is a generated protocol buffer package.

It is generated from these files:
	judge/judge.proto

It has these top-level messages:
	AccessRequest
	AccessReply
*/
package judge

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type AccessRequest struct {
	Subject  string `protobuf:"bytes,1,opt,name=subject" json:"subject,omitempty"`
	Action   string `protobuf:"bytes,2,opt,name=action" json:"action,omitempty"`
	Resource string `protobuf:"bytes,3,opt,name=resource" json:"resource,omitempty"`
	Token    string `protobuf:"bytes,4,opt,name=token" json:"token,omitempty"`
}

func (m *AccessRequest) Reset()                    { *m = AccessRequest{} }
func (m *AccessRequest) String() string            { return proto.CompactTextString(m) }
func (*AccessRequest) ProtoMessage()               {}
func (*AccessRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *AccessRequest) GetSubject() string {
	if m != nil {
		return m.Subject
	}
	return ""
}

func (m *AccessRequest) GetAction() string {
	if m != nil {
		return m.Action
	}
	return ""
}

func (m *AccessRequest) GetResource() string {
	if m != nil {
		return m.Resource
	}
	return ""
}

func (m *AccessRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type AccessReply struct {
	Allow  bool   `protobuf:"varint,1,opt,name=allow" json:"allow,omitempty"`
	Reason string `protobuf:"bytes,2,opt,name=reason" json:"reason,omitempty"`
}

func (m *AccessReply) Reset()                    { *m = AccessReply{} }
func (m *AccessReply) String() string            { return proto.CompactTextString(m) }
func (*AccessReply) ProtoMessage()               {}
func (*AccessReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *AccessReply) GetAllow() bool {
	if m != nil {
		return m.Allow
	}
	return false
}

func (m *AccessReply) GetReason() string {
	if m != nil {
		return m.Reason
	}
	return ""
}

func init() {
	proto.RegisterType((*AccessRequest)(nil), "judge.AccessRequest")
	proto.RegisterType((*AccessReply)(nil), "judge.AccessReply")
}

func init() { proto.RegisterFile("judge/judge.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 188 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x44, 0xcf, 0xc1, 0x8a, 0x83, 0x30,
	0x10, 0xc6, 0x71, 0xdc, 0x5d, 0x5d, 0x77, 0x96, 0x3d, 0x6c, 0x28, 0x12, 0x3c, 0x15, 0x4f, 0x3d,
	0xa5, 0x87, 0x1e, 0x7b, 0x6a, 0x9f, 0xa0, 0xf8, 0x06, 0x1a, 0x07, 0xd1, 0x06, 0x63, 0x33, 0x09,
	0xc5, 0xb7, 0x2f, 0x8e, 0xb5, 0xbd, 0x04, 0x7e, 0x7c, 0x81, 0x3f, 0x03, 0xff, 0x7d, 0x68, 0x5a,
	0xdc, 0xf3, 0xab, 0x46, 0x67, 0xbd, 0x15, 0x31, 0xa3, 0x20, 0xf8, 0x3b, 0x69, 0x8d, 0x44, 0x25,
	0xde, 0x02, 0x92, 0x17, 0x12, 0xbe, 0x29, 0xd4, 0x3d, 0x6a, 0x2f, 0xa3, 0x6d, 0xb4, 0xfb, 0x29,
	0x57, 0x8a, 0x0c, 0x92, 0x4a, 0xfb, 0xce, 0x0e, 0xf2, 0x83, 0x87, 0xa7, 0x44, 0x0e, 0xa9, 0x43,
	0xb2, 0xc1, 0x69, 0x94, 0x9f, 0xbc, 0xbc, 0x2c, 0x36, 0x10, 0x7b, 0x7b, 0xc5, 0x41, 0x7e, 0xf1,
	0xb0, 0xa0, 0x38, 0xc2, 0xef, 0x1a, 0x1d, 0xcd, 0x34, 0x7f, 0xaa, 0x8c, 0xb1, 0x77, 0x0e, 0xa6,
	0xe5, 0x82, 0x39, 0xe7, 0xb0, 0xa2, 0x77, 0x6e, 0xd1, 0x39, 0x87, 0x4c, 0x1b, 0x1b, 0x1a, 0x35,
	0x51, 0xe7, 0x1b, 0xd5, 0xba, 0x51, 0x2b, 0xbe, 0xe5, 0x12, 0xd5, 0x09, 0xdf, 0x76, 0x78, 0x04,
	0x00, 0x00, 0xff, 0xff, 0xe5, 0x1e, 0xa4, 0xac, 0xf0, 0x00, 0x00, 0x00,
}
