// Code generated by protoc-gen-go. DO NOT EDIT.
// source: judge/resource.proto

/*
Package judge is a generated protocol buffer package.

It is generated from these files:
	judge/resource.proto

It has these top-level messages:
	Resource
	ResourceSelector
	ResourceMutationReply
	UpdateResourceRequest
*/
package judge

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Resource struct {
	Id          string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Description string `protobuf:"bytes,2,opt,name=description" json:"description,omitempty"`
	Owner       string `protobuf:"bytes,3,opt,name=owner" json:"owner,omitempty"`
}

func (m *Resource) Reset()                    { *m = Resource{} }
func (m *Resource) String() string            { return proto.CompactTextString(m) }
func (*Resource) ProtoMessage()               {}
func (*Resource) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Resource) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Resource) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Resource) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

type ResourceSelector struct {
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
}

func (m *ResourceSelector) Reset()                    { *m = ResourceSelector{} }
func (m *ResourceSelector) String() string            { return proto.CompactTextString(m) }
func (*ResourceSelector) ProtoMessage()               {}
func (*ResourceSelector) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *ResourceSelector) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type ResourceMutationReply struct {
	Error   bool `protobuf:"varint,1,opt,name=error" json:"error,omitempty"`
	Message bool `protobuf:"varint,2,opt,name=message" json:"message,omitempty"`
}

func (m *ResourceMutationReply) Reset()                    { *m = ResourceMutationReply{} }
func (m *ResourceMutationReply) String() string            { return proto.CompactTextString(m) }
func (*ResourceMutationReply) ProtoMessage()               {}
func (*ResourceMutationReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *ResourceMutationReply) GetError() bool {
	if m != nil {
		return m.Error
	}
	return false
}

func (m *ResourceMutationReply) GetMessage() bool {
	if m != nil {
		return m.Message
	}
	return false
}

type UpdateResourceRequest struct {
	Selector *ResourceSelector `protobuf:"bytes,1,opt,name=selector" json:"selector,omitempty"`
	Content  *Resource         `protobuf:"bytes,2,opt,name=content" json:"content,omitempty"`
}

func (m *UpdateResourceRequest) Reset()                    { *m = UpdateResourceRequest{} }
func (m *UpdateResourceRequest) String() string            { return proto.CompactTextString(m) }
func (*UpdateResourceRequest) ProtoMessage()               {}
func (*UpdateResourceRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *UpdateResourceRequest) GetSelector() *ResourceSelector {
	if m != nil {
		return m.Selector
	}
	return nil
}

func (m *UpdateResourceRequest) GetContent() *Resource {
	if m != nil {
		return m.Content
	}
	return nil
}

func init() {
	proto.RegisterType((*Resource)(nil), "judge.Resource")
	proto.RegisterType((*ResourceSelector)(nil), "judge.ResourceSelector")
	proto.RegisterType((*ResourceMutationReply)(nil), "judge.ResourceMutationReply")
	proto.RegisterType((*UpdateResourceRequest)(nil), "judge.UpdateResourceRequest")
}

func init() { proto.RegisterFile("judge/resource.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 275 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x91, 0xcf, 0x4b, 0xc3, 0x30,
	0x14, 0xc7, 0x59, 0x65, 0xae, 0xbe, 0x82, 0x4a, 0xd8, 0xb4, 0xc7, 0xd1, 0x93, 0x1e, 0x96, 0xc2,
	0x76, 0xf4, 0xe6, 0x45, 0x10, 0x04, 0x89, 0x78, 0xf1, 0xd6, 0x25, 0x8f, 0x2e, 0xd2, 0x36, 0x35,
	0x3f, 0x18, 0xfb, 0xef, 0xa5, 0xaf, 0x8b, 0x48, 0x2f, 0x81, 0xf7, 0xbe, 0x9f, 0x7c, 0xde, 0x0b,
	0x81, 0xe5, 0x77, 0x50, 0x35, 0x96, 0x16, 0x9d, 0x09, 0x56, 0x22, 0xef, 0xad, 0xf1, 0x86, 0xcd,
	0xa9, 0x5b, 0x08, 0x48, 0xc5, 0x39, 0x60, 0xd7, 0x90, 0x68, 0x95, 0xcf, 0xd6, 0xb3, 0x87, 0x2b,
	0x91, 0x68, 0xc5, 0xd6, 0x90, 0x29, 0x74, 0xd2, 0xea, 0xde, 0x6b, 0xd3, 0xe5, 0x09, 0x05, 0xff,
	0x5b, 0x6c, 0x09, 0x73, 0x73, 0xec, 0xd0, 0xe6, 0x17, 0x94, 0x8d, 0x45, 0x51, 0xc0, 0x6d, 0x74,
	0x7e, 0x60, 0x83, 0xd2, 0x1b, 0x3b, 0x75, 0x17, 0x2f, 0xb0, 0x8a, 0xcc, 0x5b, 0xf0, 0xd5, 0x60,
	0x13, 0xd8, 0x37, 0xa7, 0x41, 0x89, 0xd6, 0x1a, 0x4b, 0x6c, 0x2a, 0xc6, 0x82, 0xe5, 0xb0, 0x68,
	0xd1, 0xb9, 0xaa, 0x46, 0x5a, 0x23, 0x15, 0xb1, 0x2c, 0x8e, 0xb0, 0xfa, 0xec, 0x55, 0xe5, 0x31,
	0xea, 0x04, 0xfe, 0x04, 0x74, 0x9e, 0xed, 0x20, 0x75, 0xe7, 0xe9, 0xe4, 0xca, 0xb6, 0xf7, 0x9c,
	0xde, 0xcc, 0xa7, 0xcb, 0x89, 0x3f, 0x90, 0x3d, 0xc2, 0x42, 0x9a, 0xce, 0x63, 0xe7, 0x69, 0x4e,
	0xb6, 0xbd, 0x99, 0xdc, 0x11, 0x31, 0x7f, 0x7e, 0x85, 0x3b, 0xd9, 0x98, 0xa0, 0xf8, 0xc9, 0x69,
	0xaf, 0x78, 0x6d, 0x7b, 0x39, 0xb2, 0xef, 0xb3, 0x2f, 0x5e, 0x6b, 0x7f, 0x08, 0x7b, 0x2e, 0x4d,
	0x5b, 0x52, 0xbc, 0x21, 0xb4, 0x1c, 0xa0, 0x8d, 0x93, 0x07, 0x6c, 0xab, 0x92, 0xd8, 0x27, 0x3a,
	0xf7, 0x97, 0xf4, 0x27, 0xbb, 0xdf, 0x00, 0x00, 0x00, 0xff, 0xff, 0xab, 0xb8, 0x08, 0x04, 0xab,
	0x01, 0x00, 0x00,
}
