// Code generated by protoc-gen-go. DO NOT EDIT.
// source: judge/subject.proto

/*
Package judge is a generated protocol buffer package.

It is generated from these files:
	judge/subject.proto

It has these top-level messages:
	Subject
	SubjectSelector
	UpdateSubjectRequest
	SubjectMutationReply
*/
package judge

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type SubjectType int32

const (
	SubjectType_APP  SubjectType = 0
	SubjectType_USER SubjectType = 1
)

var SubjectType_name = map[int32]string{
	0: "APP",
	1: "USER",
}
var SubjectType_value = map[string]int32{
	"APP":  0,
	"USER": 1,
}

func (x SubjectType) String() string {
	return proto.EnumName(SubjectType_name, int32(x))
}
func (SubjectType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type Subject struct {
	Id   string      `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Type SubjectType `protobuf:"varint,2,opt,name=type,enum=judge.SubjectType" json:"type,omitempty"`
}

func (m *Subject) Reset()                    { *m = Subject{} }
func (m *Subject) String() string            { return proto.CompactTextString(m) }
func (*Subject) ProtoMessage()               {}
func (*Subject) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Subject) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Subject) GetType() SubjectType {
	if m != nil {
		return m.Type
	}
	return SubjectType_APP
}

type SubjectSelector struct {
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
}

func (m *SubjectSelector) Reset()                    { *m = SubjectSelector{} }
func (m *SubjectSelector) String() string            { return proto.CompactTextString(m) }
func (*SubjectSelector) ProtoMessage()               {}
func (*SubjectSelector) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *SubjectSelector) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type UpdateSubjectRequest struct {
	Selector *SubjectSelector `protobuf:"bytes,1,opt,name=selector" json:"selector,omitempty"`
	Content  *Subject         `protobuf:"bytes,2,opt,name=content" json:"content,omitempty"`
}

func (m *UpdateSubjectRequest) Reset()                    { *m = UpdateSubjectRequest{} }
func (m *UpdateSubjectRequest) String() string            { return proto.CompactTextString(m) }
func (*UpdateSubjectRequest) ProtoMessage()               {}
func (*UpdateSubjectRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *UpdateSubjectRequest) GetSelector() *SubjectSelector {
	if m != nil {
		return m.Selector
	}
	return nil
}

func (m *UpdateSubjectRequest) GetContent() *Subject {
	if m != nil {
		return m.Content
	}
	return nil
}

type SubjectMutationReply struct {
	Error   bool `protobuf:"varint,1,opt,name=error" json:"error,omitempty"`
	Message bool `protobuf:"varint,2,opt,name=message" json:"message,omitempty"`
}

func (m *SubjectMutationReply) Reset()                    { *m = SubjectMutationReply{} }
func (m *SubjectMutationReply) String() string            { return proto.CompactTextString(m) }
func (*SubjectMutationReply) ProtoMessage()               {}
func (*SubjectMutationReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *SubjectMutationReply) GetError() bool {
	if m != nil {
		return m.Error
	}
	return false
}

func (m *SubjectMutationReply) GetMessage() bool {
	if m != nil {
		return m.Message
	}
	return false
}

func init() {
	proto.RegisterType((*Subject)(nil), "judge.Subject")
	proto.RegisterType((*SubjectSelector)(nil), "judge.SubjectSelector")
	proto.RegisterType((*UpdateSubjectRequest)(nil), "judge.UpdateSubjectRequest")
	proto.RegisterType((*SubjectMutationReply)(nil), "judge.SubjectMutationReply")
	proto.RegisterEnum("judge.SubjectType", SubjectType_name, SubjectType_value)
}

func init() { proto.RegisterFile("judge/subject.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 265 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x90, 0xc1, 0x4e, 0xbb, 0x40,
	0x10, 0xc6, 0xff, 0xf0, 0x6f, 0x05, 0x87, 0x04, 0x9b, 0x95, 0x34, 0xc4, 0x13, 0x72, 0x30, 0xc4,
	0x03, 0x26, 0xf8, 0x04, 0x35, 0xd1, 0x9b, 0x09, 0x59, 0xec, 0x03, 0x50, 0x76, 0x42, 0x68, 0x90,
	0x5d, 0xd9, 0xe1, 0xc0, 0xdb, 0x9b, 0x2c, 0x8b, 0xb1, 0x1e, 0xe7, 0x9b, 0xdf, 0x37, 0x33, 0xdf,
	0xc0, 0xed, 0x79, 0x12, 0x2d, 0x3e, 0xe9, 0xe9, 0x74, 0xc6, 0x86, 0x72, 0x35, 0x4a, 0x92, 0x6c,
	0x6b, 0xc4, 0xf4, 0x00, 0x5e, 0xb5, 0xe8, 0x2c, 0x04, 0xb7, 0x13, 0xb1, 0x93, 0x38, 0xd9, 0x35,
	0x77, 0x3b, 0xc1, 0x1e, 0x60, 0x43, 0xb3, 0xc2, 0xd8, 0x4d, 0x9c, 0x2c, 0x2c, 0x58, 0x6e, 0x0c,
	0xb9, 0xa5, 0x3f, 0x66, 0x85, 0xdc, 0xf4, 0xd3, 0x7b, 0xb8, 0xb1, 0x62, 0x85, 0x3d, 0x36, 0x24,
	0xc7, 0xbf, 0xa3, 0x52, 0x82, 0xe8, 0xa8, 0x44, 0x4d, 0x68, 0x41, 0x8e, 0x5f, 0x13, 0x6a, 0x62,
	0x05, 0xf8, 0xda, 0x7a, 0x0c, 0x1d, 0x14, 0xfb, 0xcb, 0x35, 0xeb, 0x44, 0xfe, 0xc3, 0xb1, 0x0c,
	0xbc, 0x46, 0x0e, 0x84, 0x03, 0x99, 0xcb, 0x82, 0x22, 0xbc, 0xb4, 0xf0, 0xb5, 0x9d, 0xbe, 0x41,
	0x64, 0xb5, 0xf7, 0x89, 0x6a, 0xea, 0xe4, 0xc0, 0x51, 0xf5, 0x33, 0x8b, 0x60, 0x8b, 0xe3, 0x68,
	0x57, 0xfa, 0x7c, 0x29, 0x58, 0x0c, 0xde, 0x27, 0x6a, 0x5d, 0xb7, 0x4b, 0x62, 0x9f, 0xaf, 0xe5,
	0x63, 0x02, 0xc1, 0xaf, 0xd4, 0xcc, 0x83, 0xff, 0x87, 0xb2, 0xdc, 0xfd, 0x63, 0x3e, 0x6c, 0x8e,
	0xd5, 0x2b, 0xdf, 0x39, 0x2f, 0x77, 0xb0, 0x6f, 0x7a, 0x39, 0x89, 0x7c, 0xd6, 0x1d, 0x89, 0xbc,
	0x1d, 0x55, 0xb3, 0x1c, 0x55, 0x3a, 0xa7, 0x2b, 0xf3, 0xef, 0xe7, 0xef, 0x00, 0x00, 0x00, 0xff,
	0xff, 0x7d, 0x9d, 0xdb, 0xd4, 0x86, 0x01, 0x00, 0x00,
}
