# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: account/actions/account.proto

require 'google/protobuf'

require 'account/models/types_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "account.ValidateUserRequest" do
    optional :username, :string, 1
    optional :password, :string, 2
  end
  add_message "account.ValidateUserReply" do
    optional :valid, :bool, 1
    optional :user, :message, 2, "account.User"
  end
end

module Account
  ValidateUserRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("account.ValidateUserRequest").msgclass
  ValidateUserReply = Google::Protobuf::DescriptorPool.generated_pool.lookup("account.ValidateUserReply").msgclass
end
