# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: judge/models/types.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='judge/models/types.proto',
  package='judge',
  syntax='proto3',
  serialized_pb=_b('\n\x18judge/models/types.proto\x12\x05judge\"7\n\x07Subject\x12\n\n\x02id\x18\x01 \x01(\t\x12 \n\x04type\x18\x02 \x01(\x0e\x32\x12.judge.SubjectType\"\x1d\n\x0fSubjectSelector\x12\n\n\x02id\x18\x01 \x01(\t\"a\n\x14UpdateSubjectRequest\x12(\n\x08selector\x18\x01 \x01(\x0b\x32\x16.judge.SubjectSelector\x12\x1f\n\x07\x63ontent\x18\x02 \x01(\x0b\x32\x0e.judge.Subject\"6\n\x14SubjectMutationReply\x12\r\n\x05\x65rror\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\":\n\x08Resource\x12\n\n\x02id\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\x12\r\n\x05owner\x18\x03 \x01(\t\"\x1e\n\x10ResourceSelector\x12\n\n\x02id\x18\x01 \x01(\t\"7\n\x15ResourceMutationReply\x12\r\n\x05\x65rror\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"d\n\x15UpdateResourceRequest\x12)\n\x08selector\x18\x01 \x01(\x0b\x32\x17.judge.ResourceSelector\x12 \n\x07\x63ontent\x18\x02 \x01(\x0b\x32\x0f.judge.Resource* \n\x0bSubjectType\x12\x07\n\x03\x41PP\x10\x00\x12\x08\n\x04USER\x10\x01\x42K\n\x16\x63loud.ysitd.grpc.judgeP\x01Z/github.com/ysitd-cloud/grpc-schema/judge/modelsb\x06proto3')
)

_SUBJECTTYPE = _descriptor.EnumDescriptor(
  name='SubjectType',
  full_name='judge.SubjectType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='APP', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='USER', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=529,
  serialized_end=561,
)
_sym_db.RegisterEnumDescriptor(_SUBJECTTYPE)

SubjectType = enum_type_wrapper.EnumTypeWrapper(_SUBJECTTYPE)
APP = 0
USER = 1



_SUBJECT = _descriptor.Descriptor(
  name='Subject',
  full_name='judge.Subject',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='judge.Subject.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='type', full_name='judge.Subject.type', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=35,
  serialized_end=90,
)


_SUBJECTSELECTOR = _descriptor.Descriptor(
  name='SubjectSelector',
  full_name='judge.SubjectSelector',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='judge.SubjectSelector.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=92,
  serialized_end=121,
)


_UPDATESUBJECTREQUEST = _descriptor.Descriptor(
  name='UpdateSubjectRequest',
  full_name='judge.UpdateSubjectRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='selector', full_name='judge.UpdateSubjectRequest.selector', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='content', full_name='judge.UpdateSubjectRequest.content', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=123,
  serialized_end=220,
)


_SUBJECTMUTATIONREPLY = _descriptor.Descriptor(
  name='SubjectMutationReply',
  full_name='judge.SubjectMutationReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='error', full_name='judge.SubjectMutationReply.error', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='message', full_name='judge.SubjectMutationReply.message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=222,
  serialized_end=276,
)


_RESOURCE = _descriptor.Descriptor(
  name='Resource',
  full_name='judge.Resource',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='judge.Resource.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='description', full_name='judge.Resource.description', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='owner', full_name='judge.Resource.owner', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=278,
  serialized_end=336,
)


_RESOURCESELECTOR = _descriptor.Descriptor(
  name='ResourceSelector',
  full_name='judge.ResourceSelector',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='judge.ResourceSelector.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=338,
  serialized_end=368,
)


_RESOURCEMUTATIONREPLY = _descriptor.Descriptor(
  name='ResourceMutationReply',
  full_name='judge.ResourceMutationReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='error', full_name='judge.ResourceMutationReply.error', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='message', full_name='judge.ResourceMutationReply.message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=370,
  serialized_end=425,
)


_UPDATERESOURCEREQUEST = _descriptor.Descriptor(
  name='UpdateResourceRequest',
  full_name='judge.UpdateResourceRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='selector', full_name='judge.UpdateResourceRequest.selector', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='content', full_name='judge.UpdateResourceRequest.content', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=427,
  serialized_end=527,
)

_SUBJECT.fields_by_name['type'].enum_type = _SUBJECTTYPE
_UPDATESUBJECTREQUEST.fields_by_name['selector'].message_type = _SUBJECTSELECTOR
_UPDATESUBJECTREQUEST.fields_by_name['content'].message_type = _SUBJECT
_UPDATERESOURCEREQUEST.fields_by_name['selector'].message_type = _RESOURCESELECTOR
_UPDATERESOURCEREQUEST.fields_by_name['content'].message_type = _RESOURCE
DESCRIPTOR.message_types_by_name['Subject'] = _SUBJECT
DESCRIPTOR.message_types_by_name['SubjectSelector'] = _SUBJECTSELECTOR
DESCRIPTOR.message_types_by_name['UpdateSubjectRequest'] = _UPDATESUBJECTREQUEST
DESCRIPTOR.message_types_by_name['SubjectMutationReply'] = _SUBJECTMUTATIONREPLY
DESCRIPTOR.message_types_by_name['Resource'] = _RESOURCE
DESCRIPTOR.message_types_by_name['ResourceSelector'] = _RESOURCESELECTOR
DESCRIPTOR.message_types_by_name['ResourceMutationReply'] = _RESOURCEMUTATIONREPLY
DESCRIPTOR.message_types_by_name['UpdateResourceRequest'] = _UPDATERESOURCEREQUEST
DESCRIPTOR.enum_types_by_name['SubjectType'] = _SUBJECTTYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Subject = _reflection.GeneratedProtocolMessageType('Subject', (_message.Message,), dict(
  DESCRIPTOR = _SUBJECT,
  __module__ = 'judge.models.types_pb2'
  # @@protoc_insertion_point(class_scope:judge.Subject)
  ))
_sym_db.RegisterMessage(Subject)

SubjectSelector = _reflection.GeneratedProtocolMessageType('SubjectSelector', (_message.Message,), dict(
  DESCRIPTOR = _SUBJECTSELECTOR,
  __module__ = 'judge.models.types_pb2'
  # @@protoc_insertion_point(class_scope:judge.SubjectSelector)
  ))
_sym_db.RegisterMessage(SubjectSelector)

UpdateSubjectRequest = _reflection.GeneratedProtocolMessageType('UpdateSubjectRequest', (_message.Message,), dict(
  DESCRIPTOR = _UPDATESUBJECTREQUEST,
  __module__ = 'judge.models.types_pb2'
  # @@protoc_insertion_point(class_scope:judge.UpdateSubjectRequest)
  ))
_sym_db.RegisterMessage(UpdateSubjectRequest)

SubjectMutationReply = _reflection.GeneratedProtocolMessageType('SubjectMutationReply', (_message.Message,), dict(
  DESCRIPTOR = _SUBJECTMUTATIONREPLY,
  __module__ = 'judge.models.types_pb2'
  # @@protoc_insertion_point(class_scope:judge.SubjectMutationReply)
  ))
_sym_db.RegisterMessage(SubjectMutationReply)

Resource = _reflection.GeneratedProtocolMessageType('Resource', (_message.Message,), dict(
  DESCRIPTOR = _RESOURCE,
  __module__ = 'judge.models.types_pb2'
  # @@protoc_insertion_point(class_scope:judge.Resource)
  ))
_sym_db.RegisterMessage(Resource)

ResourceSelector = _reflection.GeneratedProtocolMessageType('ResourceSelector', (_message.Message,), dict(
  DESCRIPTOR = _RESOURCESELECTOR,
  __module__ = 'judge.models.types_pb2'
  # @@protoc_insertion_point(class_scope:judge.ResourceSelector)
  ))
_sym_db.RegisterMessage(ResourceSelector)

ResourceMutationReply = _reflection.GeneratedProtocolMessageType('ResourceMutationReply', (_message.Message,), dict(
  DESCRIPTOR = _RESOURCEMUTATIONREPLY,
  __module__ = 'judge.models.types_pb2'
  # @@protoc_insertion_point(class_scope:judge.ResourceMutationReply)
  ))
_sym_db.RegisterMessage(ResourceMutationReply)

UpdateResourceRequest = _reflection.GeneratedProtocolMessageType('UpdateResourceRequest', (_message.Message,), dict(
  DESCRIPTOR = _UPDATERESOURCEREQUEST,
  __module__ = 'judge.models.types_pb2'
  # @@protoc_insertion_point(class_scope:judge.UpdateResourceRequest)
  ))
_sym_db.RegisterMessage(UpdateResourceRequest)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\026cloud.ysitd.grpc.judgeP\001Z/github.com/ysitd-cloud/grpc-schema/judge/models'))
# @@protoc_insertion_point(module_scope)
