# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: judge/models/types.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "judge.Subject" do
    optional :id, :string, 1
    optional :type, :enum, 2, "judge.SubjectType"
  end
  add_message "judge.SubjectSelector" do
    optional :id, :string, 1
  end
  add_message "judge.UpdateSubjectRequest" do
    optional :selector, :message, 1, "judge.SubjectSelector"
    optional :content, :message, 2, "judge.Subject"
  end
  add_message "judge.SubjectMutationReply" do
    optional :error, :bool, 1
    optional :message, :string, 2
  end
  add_message "judge.Resource" do
    optional :id, :string, 1
    optional :description, :string, 2
    optional :owner, :string, 3
  end
  add_message "judge.ResourceSelector" do
    optional :id, :string, 1
  end
  add_message "judge.ResourceMutationReply" do
    optional :error, :bool, 1
    optional :message, :string, 2
  end
  add_message "judge.UpdateResourceRequest" do
    optional :selector, :message, 1, "judge.ResourceSelector"
    optional :content, :message, 2, "judge.Resource"
  end
  add_enum "judge.SubjectType" do
    value :APP, 0
    value :USER, 1
  end
end

module Judge
  Subject = Google::Protobuf::DescriptorPool.generated_pool.lookup("judge.Subject").msgclass
  SubjectSelector = Google::Protobuf::DescriptorPool.generated_pool.lookup("judge.SubjectSelector").msgclass
  UpdateSubjectRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("judge.UpdateSubjectRequest").msgclass
  SubjectMutationReply = Google::Protobuf::DescriptorPool.generated_pool.lookup("judge.SubjectMutationReply").msgclass
  Resource = Google::Protobuf::DescriptorPool.generated_pool.lookup("judge.Resource").msgclass
  ResourceSelector = Google::Protobuf::DescriptorPool.generated_pool.lookup("judge.ResourceSelector").msgclass
  ResourceMutationReply = Google::Protobuf::DescriptorPool.generated_pool.lookup("judge.ResourceMutationReply").msgclass
  UpdateResourceRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("judge.UpdateResourceRequest").msgclass
  SubjectType = Google::Protobuf::DescriptorPool.generated_pool.lookup("judge.SubjectType").enummodule
end
