# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: session/models/service.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "session.Service" do
    optional :name, :string, 1
    optional :token, :string, 2
  end
end

module Session
  Service = Google::Protobuf::DescriptorPool.generated_pool.lookup("session.Service").msgclass
end
