# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: session/models/session.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='session/models/session.proto',
  package='session',
  syntax='proto3',
  serialized_pb=_b('\n\x1csession/models/session.proto\x12\x07session\"!\n\x0eSessionContent\x12\x0f\n\x07\x63ontent\x18\x01 \x01(\tBO\n\x18\x63loud.ysitd.grpc.sessionP\x01Z1github.com/ysitd-cloud/grpc-schema/session/modelsb\x06proto3')
)




_SESSIONCONTENT = _descriptor.Descriptor(
  name='SessionContent',
  full_name='session.SessionContent',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='content', full_name='session.SessionContent.content', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=41,
  serialized_end=74,
)

DESCRIPTOR.message_types_by_name['SessionContent'] = _SESSIONCONTENT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SessionContent = _reflection.GeneratedProtocolMessageType('SessionContent', (_message.Message,), dict(
  DESCRIPTOR = _SESSIONCONTENT,
  __module__ = 'session.models.session_pb2'
  # @@protoc_insertion_point(class_scope:session.SessionContent)
  ))
_sym_db.RegisterMessage(SessionContent)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\030cloud.ysitd.grpc.sessionP\001Z1github.com/ysitd-cloud/grpc-schema/session/models'))
# @@protoc_insertion_point(module_scope)
