# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: session/models/session.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "session.SessionContent" do
    optional :content, :string, 1
  end
end

module Session
  SessionContent = Google::Protobuf::DescriptorPool.generated_pool.lookup("session.SessionContent").msgclass
end
