# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from account.actions import account_pb2 as account_dot_actions_dot_account__pb2


class AccountStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.validateUserPassword = channel.unary_unary(
        '/account.Account/validateUserPassword',
        request_serializer=account_dot_actions_dot_account__pb2.ValidateUserRequest.SerializeToString,
        response_deserializer=account_dot_actions_dot_account__pb2.ValidateUserReply.FromString,
        )
    self.getUserInfo = channel.unary_unary(
        '/account.Account/getUserInfo',
        request_serializer=account_dot_actions_dot_account__pb2.GetUserInfoRequest.SerializeToString,
        response_deserializer=account_dot_actions_dot_account__pb2.GetUserInfoReply.FromString,
        )
    self.getTokenInfo = channel.unary_unary(
        '/account.Account/getTokenInfo',
        request_serializer=account_dot_actions_dot_account__pb2.GetTokenInfoRequest.SerializeToString,
        response_deserializer=account_dot_actions_dot_account__pb2.GetTokenInfoReply.FromString,
        )


class AccountServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def validateUserPassword(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def getUserInfo(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def getTokenInfo(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_AccountServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'validateUserPassword': grpc.unary_unary_rpc_method_handler(
          servicer.validateUserPassword,
          request_deserializer=account_dot_actions_dot_account__pb2.ValidateUserRequest.FromString,
          response_serializer=account_dot_actions_dot_account__pb2.ValidateUserReply.SerializeToString,
      ),
      'getUserInfo': grpc.unary_unary_rpc_method_handler(
          servicer.getUserInfo,
          request_deserializer=account_dot_actions_dot_account__pb2.GetUserInfoRequest.FromString,
          response_serializer=account_dot_actions_dot_account__pb2.GetUserInfoReply.SerializeToString,
      ),
      'getTokenInfo': grpc.unary_unary_rpc_method_handler(
          servicer.getTokenInfo,
          request_deserializer=account_dot_actions_dot_account__pb2.GetTokenInfoRequest.FromString,
          response_serializer=account_dot_actions_dot_account__pb2.GetTokenInfoReply.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'account.Account', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
