# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: judge/actions/judge.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "judge.AccessRequest" do
    optional :subject, :string, 1
    optional :action, :string, 2
    optional :resource, :string, 3
    optional :token, :string, 4
  end
  add_message "judge.AccessReply" do
    optional :allow, :bool, 1
    optional :reason, :string, 2
  end
end

module Judge
  AccessRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("judge.AccessRequest").msgclass
  AccessReply = Google::Protobuf::DescriptorPool.generated_pool.lookup("judge.AccessReply").msgclass
end
