# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: session/actions/access.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from session.models import service_pb2 as session_dot_models_dot_service__pb2
from session.models import session_pb2 as session_dot_models_dot_session__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='session/actions/access.proto',
  package='session',
  syntax='proto3',
  serialized_pb=_b('\n\x1csession/actions/access.proto\x12\x07session\x1a\x1csession/models/service.proto\x1a\x1csession/models/session.proto\"c\n\x14\x43reateSessoinRequest\x12!\n\x07service\x18\x01 \x01(\x0b\x32\x10.session.Service\x12(\n\x07session\x18\x02 \x01(\x0b\x32\x17.session.SessionContent\" \n\x12\x43reateSessionReply\x12\n\n\x02id\x18\x01 \x01(\t\"B\n\x11GetSessionRequest\x12!\n\x07service\x18\x01 \x01(\x0b\x32\x10.session.Service\x12\n\n\x02id\x18\x02 \x01(\t\"K\n\x0fGetSessionReply\x12\x0e\n\x06\x65xists\x18\x01 \x01(\x08\x12(\n\x07session\x18\x02 \x01(\x0b\x32\x17.session.SessionContent\"o\n\x14UpdateSessionRequest\x12!\n\x07service\x18\x01 \x01(\x0b\x32\x10.session.Service\x12\n\n\x02id\x18\x02 \x01(\t\x12(\n\x07\x63ontent\x18\x03 \x01(\x0b\x32\x17.session.SessionContent\"%\n\x12UpdateSessionReply\x12\x0f\n\x07success\x18\x01 \x01(\x08\"E\n\x14\x44\x65leteSessionRequest\x12!\n\x07service\x18\x01 \x01(\x0b\x32\x10.session.Service\x12\n\n\x02id\x18\x02 \x01(\t\"%\n\x12\x44\x65leteSessionReply\x12\x0f\n\x07success\x18\x01 \x01(\x08\x42P\n\x18\x63loud.ysitd.grpc.sessionP\x01Z2github.com/ysitd-cloud/grpc-schema/session/actionsb\x06proto3')
  ,
  dependencies=[session_dot_models_dot_service__pb2.DESCRIPTOR,session_dot_models_dot_session__pb2.DESCRIPTOR,])




_CREATESESSOINREQUEST = _descriptor.Descriptor(
  name='CreateSessoinRequest',
  full_name='session.CreateSessoinRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='service', full_name='session.CreateSessoinRequest.service', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='session', full_name='session.CreateSessoinRequest.session', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=101,
  serialized_end=200,
)


_CREATESESSIONREPLY = _descriptor.Descriptor(
  name='CreateSessionReply',
  full_name='session.CreateSessionReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='session.CreateSessionReply.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=202,
  serialized_end=234,
)


_GETSESSIONREQUEST = _descriptor.Descriptor(
  name='GetSessionRequest',
  full_name='session.GetSessionRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='service', full_name='session.GetSessionRequest.service', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='id', full_name='session.GetSessionRequest.id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=236,
  serialized_end=302,
)


_GETSESSIONREPLY = _descriptor.Descriptor(
  name='GetSessionReply',
  full_name='session.GetSessionReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='exists', full_name='session.GetSessionReply.exists', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='session', full_name='session.GetSessionReply.session', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=304,
  serialized_end=379,
)


_UPDATESESSIONREQUEST = _descriptor.Descriptor(
  name='UpdateSessionRequest',
  full_name='session.UpdateSessionRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='service', full_name='session.UpdateSessionRequest.service', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='id', full_name='session.UpdateSessionRequest.id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='content', full_name='session.UpdateSessionRequest.content', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=381,
  serialized_end=492,
)


_UPDATESESSIONREPLY = _descriptor.Descriptor(
  name='UpdateSessionReply',
  full_name='session.UpdateSessionReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='success', full_name='session.UpdateSessionReply.success', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=494,
  serialized_end=531,
)


_DELETESESSIONREQUEST = _descriptor.Descriptor(
  name='DeleteSessionRequest',
  full_name='session.DeleteSessionRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='service', full_name='session.DeleteSessionRequest.service', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='id', full_name='session.DeleteSessionRequest.id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=533,
  serialized_end=602,
)


_DELETESESSIONREPLY = _descriptor.Descriptor(
  name='DeleteSessionReply',
  full_name='session.DeleteSessionReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='success', full_name='session.DeleteSessionReply.success', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=604,
  serialized_end=641,
)

_CREATESESSOINREQUEST.fields_by_name['service'].message_type = session_dot_models_dot_service__pb2._SERVICE
_CREATESESSOINREQUEST.fields_by_name['session'].message_type = session_dot_models_dot_session__pb2._SESSIONCONTENT
_GETSESSIONREQUEST.fields_by_name['service'].message_type = session_dot_models_dot_service__pb2._SERVICE
_GETSESSIONREPLY.fields_by_name['session'].message_type = session_dot_models_dot_session__pb2._SESSIONCONTENT
_UPDATESESSIONREQUEST.fields_by_name['service'].message_type = session_dot_models_dot_service__pb2._SERVICE
_UPDATESESSIONREQUEST.fields_by_name['content'].message_type = session_dot_models_dot_session__pb2._SESSIONCONTENT
_DELETESESSIONREQUEST.fields_by_name['service'].message_type = session_dot_models_dot_service__pb2._SERVICE
DESCRIPTOR.message_types_by_name['CreateSessoinRequest'] = _CREATESESSOINREQUEST
DESCRIPTOR.message_types_by_name['CreateSessionReply'] = _CREATESESSIONREPLY
DESCRIPTOR.message_types_by_name['GetSessionRequest'] = _GETSESSIONREQUEST
DESCRIPTOR.message_types_by_name['GetSessionReply'] = _GETSESSIONREPLY
DESCRIPTOR.message_types_by_name['UpdateSessionRequest'] = _UPDATESESSIONREQUEST
DESCRIPTOR.message_types_by_name['UpdateSessionReply'] = _UPDATESESSIONREPLY
DESCRIPTOR.message_types_by_name['DeleteSessionRequest'] = _DELETESESSIONREQUEST
DESCRIPTOR.message_types_by_name['DeleteSessionReply'] = _DELETESESSIONREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CreateSessoinRequest = _reflection.GeneratedProtocolMessageType('CreateSessoinRequest', (_message.Message,), dict(
  DESCRIPTOR = _CREATESESSOINREQUEST,
  __module__ = 'session.actions.access_pb2'
  # @@protoc_insertion_point(class_scope:session.CreateSessoinRequest)
  ))
_sym_db.RegisterMessage(CreateSessoinRequest)

CreateSessionReply = _reflection.GeneratedProtocolMessageType('CreateSessionReply', (_message.Message,), dict(
  DESCRIPTOR = _CREATESESSIONREPLY,
  __module__ = 'session.actions.access_pb2'
  # @@protoc_insertion_point(class_scope:session.CreateSessionReply)
  ))
_sym_db.RegisterMessage(CreateSessionReply)

GetSessionRequest = _reflection.GeneratedProtocolMessageType('GetSessionRequest', (_message.Message,), dict(
  DESCRIPTOR = _GETSESSIONREQUEST,
  __module__ = 'session.actions.access_pb2'
  # @@protoc_insertion_point(class_scope:session.GetSessionRequest)
  ))
_sym_db.RegisterMessage(GetSessionRequest)

GetSessionReply = _reflection.GeneratedProtocolMessageType('GetSessionReply', (_message.Message,), dict(
  DESCRIPTOR = _GETSESSIONREPLY,
  __module__ = 'session.actions.access_pb2'
  # @@protoc_insertion_point(class_scope:session.GetSessionReply)
  ))
_sym_db.RegisterMessage(GetSessionReply)

UpdateSessionRequest = _reflection.GeneratedProtocolMessageType('UpdateSessionRequest', (_message.Message,), dict(
  DESCRIPTOR = _UPDATESESSIONREQUEST,
  __module__ = 'session.actions.access_pb2'
  # @@protoc_insertion_point(class_scope:session.UpdateSessionRequest)
  ))
_sym_db.RegisterMessage(UpdateSessionRequest)

UpdateSessionReply = _reflection.GeneratedProtocolMessageType('UpdateSessionReply', (_message.Message,), dict(
  DESCRIPTOR = _UPDATESESSIONREPLY,
  __module__ = 'session.actions.access_pb2'
  # @@protoc_insertion_point(class_scope:session.UpdateSessionReply)
  ))
_sym_db.RegisterMessage(UpdateSessionReply)

DeleteSessionRequest = _reflection.GeneratedProtocolMessageType('DeleteSessionRequest', (_message.Message,), dict(
  DESCRIPTOR = _DELETESESSIONREQUEST,
  __module__ = 'session.actions.access_pb2'
  # @@protoc_insertion_point(class_scope:session.DeleteSessionRequest)
  ))
_sym_db.RegisterMessage(DeleteSessionRequest)

DeleteSessionReply = _reflection.GeneratedProtocolMessageType('DeleteSessionReply', (_message.Message,), dict(
  DESCRIPTOR = _DELETESESSIONREPLY,
  __module__ = 'session.actions.access_pb2'
  # @@protoc_insertion_point(class_scope:session.DeleteSessionReply)
  ))
_sym_db.RegisterMessage(DeleteSessionReply)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\030cloud.ysitd.grpc.sessionP\001Z2github.com/ysitd-cloud/grpc-schema/session/actions'))
# @@protoc_insertion_point(module_scope)
