# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: session/grpc.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from session.actions import access_pb2 as session_dot_actions_dot_access__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='session/grpc.proto',
  package='session',
  syntax='proto3',
  serialized_pb=_b('\n\x12session/grpc.proto\x12\x07session\x1a\x1csession/actions/access.proto2\xbc\x02\n\x07Session\x12M\n\rcreateSession\x12\x1d.session.CreateSessoinRequest\x1a\x1b.session.CreateSessionReply\"\x00\x12\x44\n\ngetSession\x12\x1a.session.GetSessionRequest\x1a\x18.session.GetSessionReply\"\x00\x12M\n\rupdateSession\x12\x1d.session.UpdateSessionRequest\x1a\x1b.session.UpdateSessionReply\"\x00\x12M\n\rdeleteSession\x12\x1d.session.DeleteSessionRequest\x1a\x1b.session.DeleteSessionReply\"\x00\x42V\n\x18\x63loud.ysitd.grpc.sessionB\x0cSessionProtoP\x01Z*github.com/ysitd-cloud/grpc-schema/sessionb\x06proto3')
  ,
  dependencies=[session_dot_actions_dot_access__pb2.DESCRIPTOR,])



_sym_db.RegisterFileDescriptor(DESCRIPTOR)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\030cloud.ysitd.grpc.sessionB\014SessionProtoP\001Z*github.com/ysitd-cloud/grpc-schema/session'))

_SESSION = _descriptor.ServiceDescriptor(
  name='Session',
  full_name='session.Session',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=62,
  serialized_end=378,
  methods=[
  _descriptor.MethodDescriptor(
    name='createSession',
    full_name='session.Session.createSession',
    index=0,
    containing_service=None,
    input_type=session_dot_actions_dot_access__pb2._CREATESESSOINREQUEST,
    output_type=session_dot_actions_dot_access__pb2._CREATESESSIONREPLY,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='getSession',
    full_name='session.Session.getSession',
    index=1,
    containing_service=None,
    input_type=session_dot_actions_dot_access__pb2._GETSESSIONREQUEST,
    output_type=session_dot_actions_dot_access__pb2._GETSESSIONREPLY,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='updateSession',
    full_name='session.Session.updateSession',
    index=2,
    containing_service=None,
    input_type=session_dot_actions_dot_access__pb2._UPDATESESSIONREQUEST,
    output_type=session_dot_actions_dot_access__pb2._UPDATESESSIONREPLY,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='deleteSession',
    full_name='session.Session.deleteSession',
    index=3,
    containing_service=None,
    input_type=session_dot_actions_dot_access__pb2._DELETESESSIONREQUEST,
    output_type=session_dot_actions_dot_access__pb2._DELETESESSIONREPLY,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_SESSION)

DESCRIPTOR.services_by_name['Session'] = _SESSION

# @@protoc_insertion_point(module_scope)
