// Code generated by protoc-gen-go. DO NOT EDIT.
// source: session/grpc.proto

/*
Package session is a generated protocol buffer package.

It is generated from these files:
	session/grpc.proto

It has these top-level messages:
*/
package session

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import session2 "github.com/ysitd-cloud/grpc-schema/session/actions"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Session service

type SessionClient interface {
	CreateSession(ctx context.Context, in *session2.CreateSessoinRequest, opts ...grpc.CallOption) (*session2.CreateSessionReply, error)
	GetSession(ctx context.Context, in *session2.GetSessionRequest, opts ...grpc.CallOption) (*session2.GetSessionReply, error)
	UpdateSession(ctx context.Context, in *session2.UpdateSessionRequest, opts ...grpc.CallOption) (*session2.UpdateSessionReply, error)
	DeleteSession(ctx context.Context, in *session2.DeleteSessionRequest, opts ...grpc.CallOption) (*session2.DeleteSessionReply, error)
}

type sessionClient struct {
	cc *grpc.ClientConn
}

func NewSessionClient(cc *grpc.ClientConn) SessionClient {
	return &sessionClient{cc}
}

func (c *sessionClient) CreateSession(ctx context.Context, in *session2.CreateSessoinRequest, opts ...grpc.CallOption) (*session2.CreateSessionReply, error) {
	out := new(session2.CreateSessionReply)
	err := grpc.Invoke(ctx, "/session.Session/createSession", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionClient) GetSession(ctx context.Context, in *session2.GetSessionRequest, opts ...grpc.CallOption) (*session2.GetSessionReply, error) {
	out := new(session2.GetSessionReply)
	err := grpc.Invoke(ctx, "/session.Session/getSession", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionClient) UpdateSession(ctx context.Context, in *session2.UpdateSessionRequest, opts ...grpc.CallOption) (*session2.UpdateSessionReply, error) {
	out := new(session2.UpdateSessionReply)
	err := grpc.Invoke(ctx, "/session.Session/updateSession", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionClient) DeleteSession(ctx context.Context, in *session2.DeleteSessionRequest, opts ...grpc.CallOption) (*session2.DeleteSessionReply, error) {
	out := new(session2.DeleteSessionReply)
	err := grpc.Invoke(ctx, "/session.Session/deleteSession", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Session service

type SessionServer interface {
	CreateSession(context.Context, *session2.CreateSessoinRequest) (*session2.CreateSessionReply, error)
	GetSession(context.Context, *session2.GetSessionRequest) (*session2.GetSessionReply, error)
	UpdateSession(context.Context, *session2.UpdateSessionRequest) (*session2.UpdateSessionReply, error)
	DeleteSession(context.Context, *session2.DeleteSessionRequest) (*session2.DeleteSessionReply, error)
}

func RegisterSessionServer(s *grpc.Server, srv SessionServer) {
	s.RegisterService(&_Session_serviceDesc, srv)
}

func _Session_CreateSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(session2.CreateSessoinRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionServer).CreateSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/session.Session/CreateSession",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionServer).CreateSession(ctx, req.(*session2.CreateSessoinRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Session_GetSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(session2.GetSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionServer).GetSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/session.Session/GetSession",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionServer).GetSession(ctx, req.(*session2.GetSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Session_UpdateSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(session2.UpdateSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionServer).UpdateSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/session.Session/UpdateSession",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionServer).UpdateSession(ctx, req.(*session2.UpdateSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Session_DeleteSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(session2.DeleteSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionServer).DeleteSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/session.Session/DeleteSession",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionServer).DeleteSession(ctx, req.(*session2.DeleteSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Session_serviceDesc = grpc.ServiceDesc{
	ServiceName: "session.Session",
	HandlerType: (*SessionServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "createSession",
			Handler:    _Session_CreateSession_Handler,
		},
		{
			MethodName: "getSession",
			Handler:    _Session_GetSession_Handler,
		},
		{
			MethodName: "updateSession",
			Handler:    _Session_UpdateSession_Handler,
		},
		{
			MethodName: "deleteSession",
			Handler:    _Session_DeleteSession_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "session/grpc.proto",
}

func init() { proto.RegisterFile("session/grpc.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 238 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x91, 0xc1, 0x4a, 0x03, 0x31,
	0x10, 0x86, 0xd5, 0x83, 0x85, 0x60, 0x2f, 0x7b, 0x2a, 0xab, 0x5e, 0x3c, 0x0a, 0xcd, 0x82, 0xbe,
	0x41, 0x2d, 0x78, 0x2a, 0x94, 0x8a, 0x1e, 0xbc, 0x6d, 0x27, 0xc3, 0x36, 0xb0, 0xcd, 0xc4, 0x9d,
	0xe4, 0xd0, 0x77, 0xf3, 0xe1, 0xc4, 0x6c, 0x12, 0x4a, 0x37, 0xd7, 0xef, 0xff, 0xff, 0x8f, 0x90,
	0x11, 0x15, 0x23, 0xb3, 0x26, 0xd3, 0x74, 0x83, 0x05, 0x69, 0x07, 0x72, 0x54, 0xcd, 0x22, 0xab,
	0x1f, 0x52, 0xd8, 0x82, 0xd3, 0x64, 0xb8, 0x69, 0x01, 0x90, 0x79, 0xac, 0xbd, 0xfc, 0xde, 0x88,
	0xd9, 0xc7, 0x58, 0xa8, 0x36, 0x62, 0x0e, 0x03, 0xb6, 0x0e, 0x13, 0x78, 0x94, 0x71, 0x2b, 0xdf,
	0x32, 0x27, 0x6d, 0x76, 0xf8, 0xe3, 0x91, 0x5d, 0x7d, 0x5f, 0x88, 0x35, 0x99, 0x1d, 0xda, 0xfe,
	0xf4, 0x74, 0x55, 0xad, 0x85, 0xe8, 0xd0, 0x25, 0x57, 0x9d, 0xcb, 0xef, 0x19, 0x26, 0xd1, 0xa2,
	0x98, 0x8d, 0x96, 0x8d, 0x98, 0x7b, 0xab, 0x8a, 0x8f, 0xfa, 0x3c, 0xe7, 0xd3, 0x47, 0x5d, 0xc4,
	0x59, 0xa7, 0xb0, 0xc7, 0x92, 0x6e, 0x7d, 0xce, 0xa7, 0xba, 0x8b, 0x38, 0xe8, 0x56, 0x5f, 0x62,
	0x01, 0x3d, 0x79, 0x25, 0x4f, 0xac, 0x9d, 0x92, 0xe1, 0xff, 0xe3, 0x60, 0x75, 0x17, 0xbb, 0xdb,
	0xff, 0x8f, 0xde, 0x5e, 0x7f, 0x3f, 0x77, 0xda, 0x1d, 0xfc, 0x5e, 0x02, 0x1d, 0x9b, 0x50, 0x5f,
	0x86, 0x69, 0x38, 0xda, 0x92, 0xe1, 0x80, 0xc7, 0xb6, 0x89, 0xdb, 0xfd, 0x6d, 0xb8, 0xce, 0xeb,
	0x5f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x5f, 0x5d, 0x07, 0x75, 0xda, 0x01, 0x00, 0x00,
}
