# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: session/grpc.proto

require 'google/protobuf'

require 'session/actions/access_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
end

module Session
end
